### ISSUE TITLE
Suggestion: Command to opt-out of NSFW

### ISSUE THREAD

**Issue by cherry2003** [MrBilly/Tr1pw1re-Bots#6]
Suggestion, not exactly issue.
Have command that lets members/guests choose to be opt-out of not from NSFW.
Can be something like this:
`!opt-out`
(command)
or
`@tr1pw1re Opt-out of NSFW`
(message to bot)

**Comment by MrBilly** [comment]
How do you feel about this
`.iam Opt-out of NSFW`
`.iamnot Opt-out of NSFW`

**Comment by cherry2003** [comment]
Approved ;)

**Comment by 820bry** [comment]
`.opt-in`/`opt-out`, second parameter can be used in the future.
Example:
`.opt-in nsfw` to opt in NSFW channel, or `.opt-out logger` to opt out logging channel

**Comment by cherry2003** [comment]
I realize maybe we could just use nadeko for this, simply by `.iam "Opt-out of NSFW"`, could add it to `.asar` :D

**Comment by MrBilly** [comment]
@cherry2003 that is how it works currently
`.iam Opt-out of NSFW`
`.iamnot Opt-out of NSFW`

**Comment by cherry2003** [comment]
Issue closed; solution to this issue is now to just use `.iam opt-out of nsfw`. You will be able to see more info about this command in `#bot-channel`'s pinned message.
