### ISSUE TITLE
.iam

### ISSUE THREAD

**Issue by cherry2003** [MrBilly/Tr1pw1re-Bots#8]
`.iam` adds Guest role but does not remove Members role.
Needs fix.

**Comment by 820bry** [comment]
`.iam` is **not** in the repository.

**Comment by cherry2003** [comment]
`.iam` works on server, try `.iam Guest`.

**Comment by cherry2003** [comment]
Issue partially fixed by `.asar Guest` and `.asar Members`. If members want to remove Members role and keep Guest could simply do `.iamnot Members` and then do `.iam Guest`.
